specfile_path: files/auto-wlr-randr.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
    owner: "nikromen"
    project: "auto-wlr-randr-git"
    branch: main
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: release
    targets:
      - fedora-all
    owner: "nikromen"
    project: "auto-wlr-randr-git"
    branch: main
    list_on_homepage: True
    preserve_project: True
