name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Run tests in container
        run: just test-in-container

  lint:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          dnf install -y pre-commit cargo git rustfmt clippy

      - name: Init git repo for pre-commit
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git init
          git add .

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
