name: Publish to Crates.io

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --all-features

      - name: Publish to crates.io
        run: cargo publish
